// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9eAE0vkF0oL-4vMBJ-P9y79Ggdo8v78I',
    appId: '1:517219400630:web:43437d3f857fe18151df17',
    messagingSenderId: '517219400630',
    projectId: 'dr-feridas-telemedicina',
    authDomain: 'dr-feridas-telemedicina.firebaseapp.com',
    storageBucket: 'dr-feridas-telemedicina.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBQuCkVmyjHy1gQQxGLXM1S9slSOzAcUo',
    appId: '1:517219400630:android:3f1256cdf84109ff51df17',
    messagingSenderId: '517219400630',
    projectId: 'dr-feridas-telemedicina',
    storageBucket: 'dr-feridas-telemedicina.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBICLwUtE-qUxuF0LOVsQ15xFFTqa_7w7I',
    appId: '1:517219400630:ios:c004e4ea0438716b51df17',
    messagingSenderId: '517219400630',
    projectId: 'dr-feridas-telemedicina',
    storageBucket: 'dr-feridas-telemedicina.firebasestorage.app',
    iosClientId: '517219400630-nn2um6jd6j0fkso33oh67svga8m1dvnp.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBICLwUtE-qUxuF0LOVsQ15xFFTqa_7w7I',
    appId: '1:517219400630:ios:c004e4ea0438716b51df17',
    messagingSenderId: '517219400630',
    projectId: 'dr-feridas-telemedicina',
    storageBucket: 'dr-feridas-telemedicina.firebasestorage.app',
    iosClientId: '517219400630-nn2um6jd6j0fkso33oh67svga8m1dvnp.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9eAE0vkF0oL-4vMBJ-P9y79Ggdo8v78I',
    appId: '1:517219400630:web:ca8c2be3563dd56e51df17',
    messagingSenderId: '517219400630',
    projectId: 'dr-feridas-telemedicina',
    authDomain: 'dr-feridas-telemedicina.firebaseapp.com',
    storageBucket: 'dr-feridas-telemedicina.firebasestorage.app',
  );
}
