name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

# Dá permissão para o bot do GitHub gravar no repositório
permissions:
  contents: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        working-directory: ./app
        run: flutter pub get

      - name: Build Web
        working-directory: ./app
        # O base-href deve ser exatamente o nome do repositório
        run: flutter build web --base-href /dr-feridas-telemedicina/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./app/build/web
